apiVersion: apps/v1
kind: Deployment
metadata:
  name: acrforaksdemo2bk-deployment
  labels:
    app: acrforaksdemo2bk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acrforaksdemo2bk
  template:
    metadata:
      labels:
        app: acrforaksdemo2bk
    spec:
      containers:
        - name: acrforaksdemo2bk-vn
          image: acrforaksdemo2bk.azurecr.io/app3/acr-app3:v1 # Update Image Name 
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:   # Update Image Pull Secret Name we creted
        - name: acrforaksdemo2bk-secret  
# To schedule pods on Azure Virtual Nodes                    
      nodeSelector:
        kubernetes.io/role: agent
        beta.kubernetes.io/os: linux
        type: virtual-kubelet
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: Exists
      - key: azure.com/aci
        effect: NoSchedule              


   