apiVersion: v1
kind: Service
metadata:
  name: acrforaksdemo2bk-loadbalancer-service
  labels:
    app: acrforaksdemo2bk
spec:
  type: LoadBalancer
  selector:
    app: acrforaksdemo2bk
  ports:
    - port: 80
      targetPort: 80
